name: color_converter
description: dart color converter library. suitable for create, convert, and edit colors. It converts all ways between RGB, CMYK, HSB, HSL, XYZ, LAB.
version: 0.2.0
homepage: https://github.com/r-mzy47/color_converter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  test: any
